name: male_flutter_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifxying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/bgLog@3x.png
   - assets/images/log@3x.png
   - assets/images/search@3x.png
   - assets/images/xueshen.png
   - assets/images/xueshen2.png 
   - assets/images/touxiang.png
   - assets/images/dizhi@3x.png  
   - assets/images/renyuan@3x.png 
   - assets/images/renwu@3x.png 
   - assets/images/meinv.png 
   - assets/images/setting@3x.png
   - assets/images/my_paper@3x.png
   - assets/images/wode_toux.png
   - assets/images/male_icon@3x.png
   - assets/images/female_icon@3x.png
   - assets/images/bianqianzhi-@3x.png
   - assets/images/fenxiang@3x.png
   - assets/images/tianchongxing-@3x.png
   - assets/images/xiaoxi@3x.png
   - assets/images/shishui@3x.png
   - assets/images/back@3x.png
   - assets/images/add_icon@3x.png
   - assets/images/faxiaoxi@3x.png
   - assets/images/invite_bg@3x.png
   - assets/images/QRcode.png
   - assets/images/pulish_bg@3x.png
   - assets/images/hook_icon@3x.png
   - assets/images/hook_icon@3x.png
   - assets/images/shuicaibi@3x.png
   - assets/images/qianbi@3x.png
   - assets/images/notebook@3x.png
   - assets/images/jianzi@3x.png
   - assets/images/mkf@3x.png
   - assets/images/biaoqing@3x.png



  



   



   


   



 





   







   



   








  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
